# Generated by Django 2.2.7 on 2019-12-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_auto_20191214_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Hero Name'),
        ),
    ]
