# Generated by Django 2.2.7 on 2019-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0003_auto_20191214_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Hero Name'),
        ),
    ]
