# Generated by Django 2.2.7 on 2019-12-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0004_auto_20191214_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='hero_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='level',
            new_name='rank_level',
        ),
    ]
