# Generated by Django 2.2.7 on 2019-12-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Player', '0003_auto_20191214_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('playerFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_from', to='Player.Player')),
                ('playerTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_to', to='Player.Player')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
